Repository cakephp/docs, pull requests merged in 2018-11, with the labels that each got.

#5884 Show how to handle a blackholed request
  en/controllers/components/security.rst
Labels: Docs Unclear, examples

#5883 Add call to parent beforeFilter()
  en/controllers/components/security.rst
Labels: Docs Unclear, examples

#5889 [ja]2.x update retrieving your data
  ja/models/retrieving-your-data.rst
Labels: Translation

#5886 Added a note to save others the same bad experiance
  en/orm/table-objects.rst
Labels: Docs Missing

#5892 [ja] update translations.
  ja/console-and-shells/server-shell.rst
  ja/core-libraries/internationalization-and-localization.rst
  ja/core-libraries/logging.rst
  ja/orm/associations.rst
  ja/orm/behaviors/counter-cache.rst
  ja/orm/database-basics.rst
  ja/orm/entities.rst
  ja/orm/query-builder.rst
  ja/orm/retrieving-data-and-resultsets.rst
Labels: Translation

#5841 Update docs for cakephp/cakephp#12486
  en/appendices/3-7-migration-guide.rst
  en/core-libraries/validation.rst
  en/orm/validation.rst
  en/tutorials-and-examples/blog/part-three.rst
Labels: Added Functionality

#5900 4.x remove invalid text about return values
  en/appendices/4-0-migration-guide.rst
Labels: Docs Incorrect
