Repository cakephp/docs, pull requests merged in 2018-09, with the labels that each got.

#5843 Some minor updates & improvements
  en/console-and-shells/plugin-shell.rst
  en/development/testing.rst
  en/plugins.rst
Labels: Docs Outdated, Docs Unclear

#5844 missing save method around `removeColumn`
  ja/migrations.rst
Labels: Translation

#5850 updated deprecated code
  en/controllers/request-response.rst
Labels: Docs Outdated

#5857 Update ru/orm/table-objects.rst
  ru/orm/table-objects.rst
Labels: Translation

#5856 Same fixes than #5854 in french
  fr/models/data-validation.rst
  fr/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
Labels: Docs Incorrect

#5859 [ja] 3.0 sync
  ja/console-and-shells/plugin-shell.rst
  ja/controllers/middleware.rst
  ja/controllers/request-response.rst
  ja/core-libraries/caching.rst
  ja/development/testing.rst
  ja/orm/behaviors/translate.rst
  ja/plugins.rst
Labels: Translation
