Repository cakephp/docs, pull requests merged in 2018-03, with the labels that each got.

#5653 Update articles-controller.rst
  zh/tutorials-and-examples/cms/articles-controller.rst
Labels: Translation

#5657 Minor corrections typos in paginator.rst [RU]
  ru/views/helpers/paginator.rst
Labels: Translation

#5665 fix typo ja docs
  ja/appendices/2-0-migration-guide.rst
  ja/console-and-shells.rst
Labels: Translation

#5661 [ja] translate phinx pages
  ja/contents.rst
  ja/phinx.rst
  ja/phinx/commands.rst
  ja/phinx/configuration.rst
  ja/phinx/migrations.rst
  ja/phinx/seeding.rst
Labels: Translation

#5668 fix "note" in authentication.rst (Ru)
  ru/controllers/components/authentication.rst
Labels: Translation

#5676 Update validation.rst
  en/orm/validation.rst
Labels: Docs Incorrect

#5680 update authentication.rst
  zh/tutorials-and-examples/cms/authentication.rst
Labels: Translation

#5684 Translation plugins.rst into Ru
  en/plugins.rst
Labels: Translation

#5682 [ru] Translation of the helpers.rst
  ru/views/helpers.rst
Labels: Translation

#5683 Maybe need to add conventions about plugins?
  en/intro/conventions.rst
Labels: RFC

#5695 [ja] Fix typo
  ja/core-libraries/validation.rst
Labels: Translation

#5697 setErrors doesn't have to be defined anymore
  en/core-libraries/form.rst
Labels: Docs Missing

#5696 #Ru Updated conventions.rst in accordance with SRC
  ru/intro/conventions.rst
Labels: Translation
