Repository cakephp/docs, pull requests merged in 2018-05, with the labels that each got.

#5731 Routing middleware
  en/controllers/middleware.rst
  en/development/routing.rst
Labels: Docs Missing, Docs Unclear

#5742 Add note about bail early principle.
  en/contributing/cakephp-coding-conventions.rst
Labels: Coding Standards

#5737 [ja] translate 3.6 migration guide.
  ja/appendices/3-6-migration-guide.rst
  ja/appendices/3-x-migration-guide.rst
  ja/console-and-shells.rst
  ja/console-and-shells/commands.rst
  ja/console-and-shells/helpers.rst
  ja/console-and-shells/input-output.rst
  ja/console-and-shells/option-parsers.rst
  ja/console-and-shells/orm-cache.rst
  ja/console-and-shells/schema-cache.rst
  ja/console-and-shells/shells.rst
  ja/development/routing.rst
  ja/development/testing.rst
  ja/plugins.rst
Labels: Translation

#5380 begin korean documentation work
  kr/Makefile
  kr/conf.py
  kr/index.rst
  kr/installation.rst
  kr/intro.rst
  kr/intro/cakephp-folder-structure.rst
  kr/intro/where-to-get-help.rst
  kr/quickstart.rst
  kr/tutorials-and-examples/blog-auth-example/auth.rst
  kr/tutorials-and-examples/blog/blog.rst
  kr/tutorials-and-examples/blog/part-three.rst
  kr/tutorials-and-examples/blog/part-two.rst
  kr/tutorials-and-examples/bookmarks/intro.rst
  kr/tutorials-and-examples/bookmarks/part-two.rst
  kr/tutorials-and-examples/cms/articles-controller.rst
  kr/tutorials-and-examples/cms/authentication.rst
  kr/tutorials-and-examples/cms/database.rst
  kr/tutorials-and-examples/cms/installation.rst
  kr/tutorials-and-examples/cms/tags-and-users.rst
Labels: Translation

#5757 Translation to pt_BR
  pt/orm/behaviors/tree.rst
Labels: Translation
