Repository cakephp/docs, pull requests merged in 2019-04, with the labels that each got.

#6005 Improve Shell deprecation/replacement visiblity
  en/appendices/3-6-migration-guide.rst
  en/console-and-shells.rst
  en/console-and-shells/commands.rst
Labels: Docs Unclear

#6006 Add missing but pre-existing Console folder
  en/intro/cakephp-folder-structure.rst
Labels: Docs Unclear

#6007 Add note about the non-pre-exiting folders in src
  en/intro/cakephp-folder-structure.rst
Labels: Docs Unclear

#5981 Update tree.rst
  en/orm/behaviors/tree.rst
Labels: examples

#6019 Correct outdated statement about _seralize
  en/views/json-and-xml-views.rst
Labels: Docs Outdated

#6041 Improve date & time parts keys discoverability
  en/views/helpers/form.rst
Labels: Docs Unclear

#6042 Make date control input example more clear
  en/views/helpers/form.rst
Labels: Docs Unclear, examples

#6036 Mark authcomponent as deprecated
  en/contents.rst
  en/controllers/components/authentication.rst
Labels: Deprecations
