Repository cakephp/docs, pull requests merged in 2019-12, with the labels that each got.

#6294 Some 2.x EOL notes/warnings.
  en/installation.rst
Labels: Deprecations

#6302 4.x: Fix up newEmptyEntity() usage.
  en/controllers/components.rst
  en/controllers/components/authentication.rst
  en/controllers/components/request-handling.rst
  en/core-libraries/email.rst
  en/core-libraries/form.rst
  en/intro.rst
  en/orm/entities.rst
  en/orm/saving-data.rst
  en/tutorials-and-examples/blog-auth-example/auth.rst
  en/tutorials-and-examples/blog/part-three.rst
  en/tutorials-and-examples/blog/part-two.rst
  en/tutorials-and-examples/cms/authentication.rst
  en/views/cells.rst
  en/views/helpers.rst
Labels: Docs Incorrect

#6318 Improve documentation about cacheMetadata
  en/orm/database-basics.rst
Labels: Docs Unclear
