Repository cakephp/docs, pull requests merged in 2019-06, with the labels that each got.

#6101 Create commands.rst
  es/phinx/commands.rst
Labels: Translation

#6110 Add example for postLink()
  en/views/helpers/form.rst
Labels: Docs Missing

#6116 Update depr docs.
  en/appendices/4-0-migration-guide.rst
Labels: Deprecations

#6121 Translation of controllers/middleware.rst
  es/_static/img/middleware-request.png
  es/_static/img/middleware-setup.png
  es/controllers/middleware.rst
Labels: Translation
