Repository cakephp/docs, pull requests merged in 2019-01, with the labels that each got.

#5873 add info on how to paginate the same model multiple times
  en/controllers/components/pagination.rst
Labels: Docs Missing, examples

#5897 3.0 plugin testing
  en/appendices/3-6-migration-guide.rst
  en/development/testing.rst
  en/plugins.rst
Labels: Docs Missing

#5925 [ja] modify testing - about IntegrationTestCase is moved
  ja/development/testing.rst
Labels: Translation

#5926 [ja] fix console-and-shells testing chapter (use ConsoleIntegrationTestTrait)
  ja/console-and-shells/commands.rst
Labels: Translation

#5928 [ja]translate and fix testing.rst to use IntegrationTestTrait in controller integrating test
  ja/development/testing.rst
Labels: Translation

#5927 autoload is not available with addPlugin
  en/plugins.rst
Labels: Docs Incorrect

#5942 [ja] Add translation to testing.rst to add test suite methods
  ja/development/testing.rst
Labels: Translation

#5943 Fix link to php.net and update translations.
  en/development/configuration.rst
  ja/bake.rst
  ja/console-and-shells/plugin-shell.rst
  ja/debug-kit.rst
  ja/development/configuration.rst
  ja/elasticsearch.rst
  ja/migrations.rst
  ja/plugins.rst
  ja/tutorials-and-examples/blog/part-three.rst
  ja/views/themes.rst
Labels: Translation

#5950 3.7 migration guide in Japanese
  en/appendices/3-7-migration-guide.rst
  ja/appendices/3-7-migration-guide.rst
  ja/appendices/3-x-migration-guide.rst
Labels: Translation

#5958 Add TLD whitelisting as preferred debugkit enable.
  en/debug-kit.rst
Labels: Docs Outdated
