Repository cakephp/docs, pull requests merged in 2020-03, with the labels that each got.

#6522 Move Chronos to Standalone Packages
  en/contents.rst
Labels: Docs Incorrect, needs-fr-translation, needs-ja-translation

#6546 [3.x] Use spelled out variable names in DB basics
  en/orm/database-basics.rst
Labels: Docs Unclear, examples

#6548 Fixing middleware typos and signature errors.
  en/controllers/middleware.rst
Labels: Docs Incorrect

#6545 [4.x] Use spelled out variable names in DB basics
  en/orm/database-basics.rst
  fr/orm/database-basics.rst
  ja/orm/database-basics.rst
  pt/orm/database-basics.rst
  ru/orm/database-basics.rst
  tl/orm/database-basics.rst
Labels: Docs Unclear, examples

#6547 Fix up missing docs for getParsedBody().
  en/controllers/request-response.rst
Labels: Docs Missing
