Repository cakephp/docs, pull requests merged in 2020-04, with the labels that each got.

#6582 Fix up return typehints and doc issues.
  en/console-commands/commands.rst
  en/console-commands/option-parsers.rst
  en/controllers/components/pagination.rst
  en/core-libraries/validation.rst
  en/development/sessions.rst
  en/development/testing.rst
  en/orm/table-objects.rst
  en/orm/validation.rst
  en/tutorials-and-examples/blog-auth-example/auth.rst
  en/tutorials-and-examples/blog/part-three.rst
  en/tutorials-and-examples/blog/part-two.rst
  en/views/helpers.rst
  en/views/helpers/form.rst
Labels: Docs Outdated

#6586 Include `Layout` as lowercased template folder
  en/appendices/4-0-migration-guide.rst
Labels: Docs Missing

#6585 Fix __d() domain docs.
  en/core-libraries/global-constants-and-functions.rst
Labels: Docs Incorrect

#6593 Some docs about pathUrl().
  en/development/routing.rst
  en/views.rst
  en/views/helpers/url.rst
Labels: Docs Missing
