Repository cakephp/docs, pull requests merged in 2022-10, with the labels that each got.

#7517 Correct isUnique() rule example
  en/orm/validation.rst
Labels: Docs Incorrect, examples

#7522 4.x Do not use apostrophe for plurals
  en/appendices/glossary.rst
  en/console-commands/repl.rst
  en/contributing/code.rst
  en/core-libraries/caching.rst
  en/core-libraries/email.rst
  en/core-libraries/httpclient.rst
  en/core-libraries/xml.rst
  en/development/routing.rst
  en/views.rst
  en/views/helpers/url.rst
Labels: Docs Unclear

#7523 3.x Do not use apostrophe for plurals
  en/appendices/glossary.rst
  en/console-and-shells/repl.rst
  en/contributing/code.rst
  en/core-libraries/caching.rst
  en/core-libraries/email.rst
  en/core-libraries/httpclient.rst
  en/core-libraries/xml.rst
  en/development/routing.rst
  en/views.rst
  en/views/helpers/url.rst
Labels: Docs Unclear

#7518 Mention that _properties has been renamed to _fields
  en/appendices/4-0-migration-guide.rst
Labels: Docs Missing

#7520 3.x Create Project with CakePHP 3.10 for General Installation correctly
  en/installation.rst
Labels: Docs Incorrect, Docs Outdated, examples

#7519 3.x Create Project for Tutorials with CakePHP 3.10 correctly
  en/tutorials-and-examples/blog/blog.rst
  en/tutorials-and-examples/bookmarks/intro.rst
  en/tutorials-and-examples/cms/installation.rst
Labels: Docs Incorrect, Docs Outdated, examples
